#!/usr/bin/env bash
#configures a brand new ubuntu machine, i.e installs nginx and configures it

NGINX_CONFIG='/etc/nginx/sites-available/default'
DEFAULT_ROOT='/var/www/html'
NEW_ROOT='/usr/share/nginx/html'
BACKUP_INDEX="${NEW_ROOT}/index.txt"
INDEX_PAGE="${NEW_ROOT}/index.html"
ERROR_PAGE="${NEW_ROOT}/404.html"

apt-get -y update
apt-get -y install nginx

#Backup the default index page
if [ -e "$NGINX_CONFIG" ]; then
        sed -i "s|root ${DEFAULT_ROOT}|root ${NEW_ROOT}|" "${NGINX_CONFIG}"
else
        echo "Missing configuration file" >&2
        exit 1
fi

#Backup the default index page
if [ -e "$INDEX_PAGE" ]; then
        mv "$INDEX_PAGE" "$BACKUP_INDEX"
fi

echo "Hello World!" > "$INDEX_PAGE"
echo "Ceci n'est pas une page" > "$ERROR_PAGE"

#Permanently redirect /redirect_me and 404 errors to /404.html
sed -i '/server_name _;/!b;
        a\
\
        # Add custom 404 page\
\
        error_page 404 /404.html;\
\
        location = /404.html {\
                internal;\
        }\
\
        # Add redirect for /redirect_me\
\
        location /redirect_me {\
                rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\
        }
' "$NGINX_CONFIG"

service nginx restart
